# Generated by Django 2.1 on 2019-09-08 01:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rezervacije', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rezervacija',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_rezervacije', models.DateField()),
                ('pocetak_rezervacije', models.IntegerField()),
                ('kraj_rezervacije', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broj_stola', models.IntegerField()),
                ('broj_stolica', models.IntegerField()),
                ('lokacija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rezervacije.Lokacija')),
            ],
        ),
        migrations.AddField(
            model_name='rezervacija',
            name='stol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rezervacije.Stol'),
        ),
    ]
