# Generated by Django 2.1 on 2019-09-08 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rezervacije', '0002_auto_20190908_0302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lokacija',
            options={'verbose_name_plural': 'Lokacije'},
        ),
        migrations.AlterModelOptions(
            name='rezervacija',
            options={'verbose_name_plural': 'Rezervacije'},
        ),
        migrations.AlterModelOptions(
            name='stol',
            options={'verbose_name_plural': 'Stolovi'},
        ),
    ]
