# Generated by Django 2.1 on 2019-09-12 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jelovnik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=45)),
                ('vrsta', models.CharField(max_length=45)),
                ('cijena', models.CharField(blank=True, max_length=45, null=True)),
                ('sastojci', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
