# Generated by Django 2.1 on 2019-09-12 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jelovnici', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jelovnik',
            options={'verbose_name_plural': 'Jelovnik'},
        ),
    ]
