# Generated by Django 2.1 on 2019-09-12 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jelovnici', '0003_jelovnik_dnevna_ponuda'),
    ]

    operations = [
        migrations.AddField(
            model_name='jelovnik',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='image/'),
        ),
    ]
